"""Ingest FoldX data from OTAR2081 project."""

from __future__ import annotations

from typing import TYPE_CHECKING, Annotated

from pydantic import BaseModel, Field

from gentropy.common.session import Session
from gentropy.datasource.open_targets.foldex_integration import OpenTargetsFoldX

if TYPE_CHECKING:
    from gentropy.dataset.amino_acid_variants import AminoAcidVariants


class FoldXIngestionDefaults(BaseModel, frozen=True):
    """Defaults for FoldXIngestionStep.

    All values are frozen - create a new instance to override.
    """

    foldx_dataset_path: Annotated[str, Field(description="Path to the FoldX dataset.")]
    plddt_threshold: Annotated[
        float,
        Field(
            description="PLDDT threshold to filter amino acids in the structural model."
        ),
    ]
    annotation_path: Annotated[str, Field(description="Path of the output dataset.")]


class FoldXIngestionStep:
    """Step to ingest proteome-wide FoldX dataset generated by the OTAR2081 project."""

    def __init__(
        self,
        session: Session,
        config: FoldXIngestionDefaults,
    ) -> None:
        """Initialize step.

        Args:
            session: Session object.
            config: Configuration for the step.
        """
        fold_x_data = session.spark.read.parquet(config.foldx_dataset_path)
        # Transform
        gene_index: AminoAcidVariants = OpenTargetsFoldX.ingest_foldx_data(
            fold_x_data, config.plddt_threshold
        )
        # Load
        gene_index.df.coalesce(session.output_partitions).write.mode(
            session.write_mode
        ).parquet(config.annotation_path)
