"""Ingest Loss-of-Function variant data generated by OTAR2075."""

from typing import Annotated

from pydantic import BaseModel, Field

from gentropy.common.session import Session
from gentropy.datasource.open_targets.lof_curation import OpenTargetsLOF


class LOFIngestionDefaults(BaseModel, frozen=True):
    """Defaults for LOFIngestionStep.

    All values are frozen - create a new instance to override.
    """

    lof_curation_dataset_path: Annotated[
        str, Field(description="Path of the curated LOF dataset.")
    ]
    lof_curation_variant_annotations_path: Annotated[
        str, Field(description="Path of the resulting variant annotations.")
    ]


class LOFIngestionStep:
    """Step to ingest the Loss-of-Function dataset generated by OTAR2075."""

    def __init__(
        self,
        session: Session,
        config: LOFIngestionDefaults,
    ) -> None:
        """Initialize step.

        Args:
            session (Session): Session object.
            config: Configuration for the step.
        """
        # Read in data:
        lof_dataset = session.spark.read.csv(
            config.lof_curation_dataset_path, sep=",", header=True, multiLine=True
        )
        # Extract relevant information to a VariantIndex
        lof_variant_annotations = OpenTargetsLOF.as_variant_index(lof_dataset)
        # Write to file:
        (
            lof_variant_annotations.df.coalesce(session.output_partitions)
            .write.mode(session.write_mode)
            .parquet(config.lof_curation_variant_annotations_path)
        )
