site_name: Open Targets Gentropy

nav:
  - Home: index.md
  - Installation: installation.md
  - ... | howto/**
  - ... | development/**
  - ... | python_api/**

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
  - mkdocstrings:
      handlers:
        python:
          options:
            filters: ["!^_", "!__new__", "__init__"]
            show_signature_annotations: true
            show_root_heading: true
  - section-index
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      exclude:
        - index.md
  - autolinks
  - exclude:
      glob:
        - assets/schemas/*
  # Show git commiters in the footer
  - git-committers:
      repository: opentargets/gentropy
      branch: main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: "docs"
      dedent_subsections: true
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
hooks:
  - src/utils/schemadocs.py

repo_name: opentargets/gentropy
repo_url: https://github.com/opentargets/gentropy

theme:
  name: "material"
  favicon: assets/imgs/favicon.png
  logo: assets/imgs/otlogo.png
  custom_dir: docs/assets/overrides

  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gentropy

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
