"""deCODE ingestion manifest.

The `deCODEManifest` dataset catalogues every summary-statistics file available
in the deCODE S3 bucket. It is generated by listing the bucket directly via the
Hadoop S3A FileSystem API and is subsequently consumed by downstream ingestion steps
to locate per-study TSV gzip files and to associate each assay with a project identifier.
"""

from __future__ import annotations

from pyspark.sql import functions as f
from pyspark.sql import types as t

from gentropy import Session
from gentropy.dataset.dataset import Dataset
from gentropy.datasource.decode import deCODEDataSource


class deCODEManifest(Dataset):
    """Catalogue of deCODE summary-statistics files derived from an S3 bucket listing.

    Each row corresponds to one SomaScan assay and records the S3 path of its
    gzipped TSV summary-statistics file together with provenance metadata such as
    file size and accession timestamp.  The `studyId` follows the convention
    ``{projectId}_{Proteomics_*}`` as embedded in the file path.

    The manifest is produced by `from_s3` and later consumed by
    `deCODEStudyIndex` and `deCODESummaryStatistics`.
    """

    @classmethod
    def get_schema(cls) -> t.StructType:
        """Return the enforced Spark schema for `deCODEManifest`.

        Returns:
            t.StructType: Schema with fields ``projectId``, ``studyId``,
                ``hasSumstats``, ``summarystatsLocation``, ``size``, and
                ``accessionTimestamp``.
        """
        return t.StructType(
            [
                t.StructField("projectId", t.StringType()),
                t.StructField("studyId", t.StringType()),
                t.StructField("hasSumstats", t.BooleanType()),
                t.StructField("summarystatsLocation", t.StringType()),
                t.StructField("size", t.StringType()),
                t.StructField("accessionTimestamp", t.TimestampType()),
            ]
        )

    def get_summary_statistics_paths(self) -> list[str]:
        """Get summary statistics paths from manifest.

        Returns:
            list[str]: List of summary statistics paths.

        Examples:
            >>> data = [("path1",), ("path2",)]
            >>> schema = "summarystatsLocation STRING"
            >>> df = spark.createDataFrame(data, schema)
            >>> manifest = deCODEManifest(df)
            >>> manifest.get_summary_statistics_paths()
            ['path1', 'path2']
        """
        return [
            row.summarystatsLocation
            for row in self.df.select("summarystatsLocation").collect()
        ]

    @classmethod
    def from_s3(
        cls,
        session: Session,
        bucket_name: str,
        prefix: str = "",
    ) -> deCODEManifest:
        """Create a `deCODEManifest` by listing the S3 bucket directly via the Hadoop FileSystem API.

        Credentials (``bucket_name``, ``access_key_id``, ``secret_access_key``,
        ``s3_host_url``, ``s3_host_port``) can be requested at
        https://www.decode.com/summarydata/ and must be supplied to the session via
        ``add_s3_connector=True`` and ``s3_configuration`` (see :class:`~gentropy.external.s3.S3Config`).
        Once the session is configured, the S3A endpoint and credentials are resolved
        automatically from Hadoop's configuration.

        Args:
            session (Session): Active Gentropy Spark session with S3 connector configured.
            bucket_name (str): S3 bucket name without any URI prefix.
            prefix (str): Optional key prefix to restrict the listing (e.g. ``"Proteomics/"``).

        Returns:
            deCODEManifest: Populated manifest dataset.

        Examples:
            >>> manifest = deCODEManifest.from_s3(  # doctest: +SKIP
            ...     session=session,
            ...     bucket_name="largescaleplasma-2023",
            ... )
        """
        jvm = session.spark.sparkContext._jvm
        hadoop_conf = session.spark.sparkContext._jsc.hadoopConfiguration()

        base_uri = f"s3a://{bucket_name}/{prefix}"
        fs = jvm.org.apache.hadoop.fs.FileSystem.get(
            jvm.java.net.URI.create(base_uri),
            hadoop_conf,
        )

        iterator = fs.listFiles(jvm.org.apache.hadoop.fs.Path(base_uri), True)
        rows: list[tuple[str, str, int]] = []
        while iterator.hasNext():
            status = iterator.next()
            file_path: str = status.getPath().toString()
            if "Proteomics" in file_path and file_path.endswith(".txt.gz"):
                rows.append((
                    file_path,
                    cls._format_size_bytes(int(status.getLen())),
                    int(status.getModificationTime()),
                ))

        raw_schema = t.StructType(
            [
                t.StructField("summarystatsLocation", t.StringType()),
                t.StructField("size", t.StringType()),
                t.StructField("_modTimeMs", t.LongType()),
            ]
        )

        project_id = f.when(
            f.col("summarystatsLocation").contains("Proteomics_SMP_"),
            f.lit(deCODEDataSource.DECODE_PROTEOMICS_SMP.value),
        ).otherwise(deCODEDataSource.DECODE_PROTEOMICS_RAW.value)

        manifest_df = (
            session.spark.createDataFrame(rows, raw_schema)
            .withColumn("projectId", project_id)
            .withColumn(
                "studyId",
                f.concat_ws(
                    "_",
                    f.col("projectId"),
                    f.regexp_extract(
                        "summarystatsLocation",
                        r"^.*/(Proteomics_.*)\.txt\.gz$",
                        1,
                    ),
                ),
            )
            .withColumn("hasSumstats", f.lit(True))
            .withColumn(
                "accessionTimestamp",
                f.to_timestamp(f.col("_modTimeMs") / 1000),
            )
            .select(
                "projectId",
                "studyId",
                "hasSumstats",
                "summarystatsLocation",
                "size",
                "accessionTimestamp",
            )
        )
        return cls(_df=manifest_df)

    @staticmethod
    def _format_size_bytes(n: int) -> str:
        """Format a byte count as a human-readable string matching ``aws s3 ls --human-readable``.

        Args:
            n (int): File size in bytes.

        Returns:
            str: Human-readable size string, e.g. ``"926.0 MiB"``.

        Examples:
            >>> deCODEManifest._format_size_bytes(970_981_376)
            '926.0 MiB'
            >>> deCODEManifest._format_size_bytes(1_073_741_824)
            '1.0 GiB'
            >>> deCODEManifest._format_size_bytes(512)
            '512.0 B'
        """
        value = float(n)
        for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
            if value < 1024:
                return f"{value:.1f} {unit}"
            value /= 1024
        return f"{value:.1f} PiB"
